blogapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('main_index', views.index, name='main_index'),

    path('register', views.register, name='register'),
    path('signin', views.signin, name='signin'),
    path('home', views.home, name='home'),
    path('member', views.member, name='member'),
    path('signout', views.signout, name='signout'),
    
    path('member-list', views.member_details, name='member-list'),
    path('newcomer-list', views.newcomer_details, name='newcomer-list'),

    path('<int:ref_id>', views.activity_stream, name="activity_stream"),
    # path('activity_stream/<int:ref_id>', activity_stream_details, name="activity_stream_details"),
    # path('activity_stream/', views.signout, name='signout'),


]

multiform/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('blogapp.urls')),
    path('admin/', admin.site.urls),
]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
# Create your models here.

class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)
    # created_by = models.ForeignKey('account.User', on_delete=models.CASCADE, null=True, blank=True,
    #                                related_name='+')


CONTACTED_BY = (
    ('CALL', "CALL"),
    ('VISIT', "VISIT"),
    ('CALL_VISIT', "CALL & VISIT"),
)


PURPOSE = (
    ('INTRESTED_IN_BECOMING_A_MEMBER', "INTRESTED IN BECOMING A MEMBER"),
    ('VISING_INTRESTED_IN_BECOMING_A_MEMBER', "VISING INTRESTED IN BECOMING A MEMBER"),
    ('SEASONAL_VISITOR_BECOMING_ACTIVE', "SEASONAL VISITOR BECOMING ACTIVE"),
    ('JUST_VISITING', "JUST VISITING")
)


MEMBER_TYPE = (
    ('FULL_MEMBER', "FULL MEMBER"),
    ('ORDINARY_MEMBER', "ORDINARY_MEMBER")
)


ACTIVITY_STREAM_CHOICES = (
    ('Attempt', "Attempt"),
    ('Success', "Success"),
    ('Failed', "Failed"),
)


class NewComer(BaseModel):
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=64, null=True)
    phone =  models.CharField(max_length=64)
    home_address= models.CharField(max_length=64)
    contact_via = models.CharField(max_length=200, choices=CONTACTED_BY, default="CALL")
    invited_by = models.CharField(max_length=64, null=True)
    intrest = models.CharField(max_length=200, choices=PURPOSE, default="JUST_VISITING")
    prayer_request = models.CharField(max_length=64, null=True)
    observations = models.CharField(max_length=64, null=True)
    current_job = models.CharField(max_length=64, null=True)


    def __str__(self):
        return "%s (%s)" % (self.name, self.email)
    
    class Meta:
        verbose_name = "Newcomer List"
    
    
class Memebers(BaseModel):
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    phone =  models.CharField(max_length=64)
    home_address= models.CharField(max_length=64)
    contact_via = models.CharField(max_length=200, choices=CONTACTED_BY, default="CALL")
    memeber_type=models.CharField(max_length=200, choices=MEMBER_TYPE, default="ORDINARY_MEMBER")
    current_job = models.CharField(max_length=64, null=True)
    
    # class Meta:
    #     verbose_name = "Members List"


    def __str__(self):
        return "%s (%s)" % (self.name, self.email)
    
    
    class Meta:
            ordering = ('-created',)

class ActivityStream(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='actions', db_index=True, null=True, blank=True)
    verb = models.CharField(max_length=255)
    ref_id = models.CharField(max_length=255)
    response_status = models.CharField(max_length=20, choices=ACTIVITY_STREAM_CHOICES, default='ATTEMPT')
    
    
    def __str__(self):
        return f"{self.ref_id}"
    class Meta:
        ordering = ('-created',)

class ActivityStreamTarget(BaseModel):
    activity_stream = models.ForeignKey(ActivityStream, related_name='activitystream', on_delete=models.CASCADE)
    target_ct = models.ForeignKey(ContentType, blank=True, null=True, related_name='target_obj', on_delete=models.CASCADE)
    target_id = models.PositiveIntegerField(null=True, blank=True, db_index=True)
    target = GenericForeignKey('target_ct', 'target_id')

    def __str__(self):
        return f"{self.target_id}"

blogapp/forms.py
from django import forms
from .models import Memebers



"""
UserRegistration
username
email
password
confirm


LoginForm
username
password

"""


class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))



class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))




class MemebersForm(forms.ModelForm):
    
    class Meta:
        model = Memebers
        fields = ["name", "email", "phone", "home_address","contact_via", "memeber_type","current_job"]

blogapp/views.py
# from django.http import HttpResponse
from django.shortcuts import redirect, render
from blogapp.utils import create_activity_stream, generate_digits, update_activity_stream
from .models import ActivityStream, ActivityStreamTarget, Memebers, NewComer
from .forms import UserRegistrationForm, LoginForm, MemebersForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from blogapp.documents import ActivitystreamDocument, NewcomerDocument
# from django.contrib import messages


# Create your views here.
@login_required(login_url='signin')
def index(request):
    ref_id = generate_digits(15)
    # create_activity_stream(request.user,'New Member Registeration', ref_id, response_status='Attempt')
    if request.method == 'GET':
        print(request)
    elif request.method == 'POST':
        pst = NewComer()
        initial = {}
        name = request.POST.getlist('name')
        email = request.POST.getlist('email')
        phone = request.POST.getlist('phone')
        home_address = request.POST.getlist('home_address')
        contact_via = request.POST.getlist('contact_via')
        invited_by = request.POST.getlist('invited_by')
        intrest = request.POST.getlist('intrest')
        prayer_request = request.POST.getlist('prayer_request')
        observations = request.POST.getlist('observations')
        current_job = request.POST.getlist('current_job')

        bulk_number = request.POST.getlist('hidden_form_number')
        bulk_number = int(bulk_number[0])
        # print(bulk_number)
        
        users_created = []
        user_created_failed = []
        list_member=[]
        failed_count2=None
        

        for i in range(bulk_number):
            list_member.append(i)
            all_post = NewComer.objects.create(
                name=name[i],
                email=email[i],
                phone=phone[i],
                home_address=home_address[i],
                contact_via=contact_via[i],
                invited_by=invited_by[i],
                intrest=intrest[i],
                prayer_request=prayer_request[i],
                observations=observations[i],
                current_job=current_job[i],
            )
            if name[i] == '' or None:
                user_created_failed.append(i)
                continue 
            users_created.append(all_post)
            
            # print(name[i])
            # print(email[i])
        users_count = len(users_created)
        failed_count = len(user_created_failed)
        passed_count= users_count - failed_count
        print(users_count)
        print(failed_count)
       
        # print(f"total passed count {passed_count}")
        all_post.save()
        
        # print(users_count)
    # create_activity_stream(request.user,'New Member Registeration', ref_id, response_status='Attempt')
        create_activity_stream(request.user, f"{users_count} New Comers registered and {failed_count} registration failed",
                               ref_id, 'Success', target=users_created)
        return redirect('home')
    return render(request, 'multForm/index.html')


def register(request):
    ref_id = generate_digits(15)
    # create_activity_stream(
    #     request.user, 'Registration Attempt', ref_id, response_status='Attempt')

    if request.user.is_authenticated:
        return redirect('home')
    form = UserRegistrationForm()
    if request.method == 'POST':
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        confirm = request.POST["confirm"]
        if password == confirm:
            new_user = User.objects.create_user(
                username=username,
                email=email,
                password=password,

            )
            new_user.set_password(password)
            new_user.save()
            # update_activity_stream(ref_id, "Registered",
            #                        'Success', target=new_user)
            return redirect('home')
        # update_activity_stream(ref_id, "Failed Registration", 'Failed')
    context = {
        'form': form
    }
    return render(request, 'multForm/register.html', context)


def signin(request):
    ref_id = generate_digits(15)
    print(ref_id)
    # create_activity_stream(request.user,'New Member Registeration', ref_id, response_status='Attempt')
    # create_activity_stream(request.user, 'Sign In Attempt',
    #                        ref_id, response_status='Attempt')
    # activity_stream_ref_id = str(timezone.now().timestamp()).replace('.', '')
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            create_activity_stream(request.user, f"{user.first_name} {user.last_name} Logged In",
                               ref_id, 'Success', target=user)
            # update_activity_stream(ref_id, "logged In",
            #                        'Success', user=request.user, target=user)
            return redirect('home')
        else:
            context = {
                'form': form,
                'error': 'User not found'
            }
            # update_activity_stream(ref_id, "Failed Login", 'Failed')
            return render(request, 'multForm/login.html', context)
    context = {
        'form': form,
    }
    return render(request, 'multForm/login.html', context)


@login_required(login_url='signin')
def member(request):
    ref_id = generate_digits(15)
    # create_activity_stream(
    #     request.user, 'Attempt Member Registration', ref_id, response_status='Attempt')
    form = MemebersForm()
    if request.method == 'POST':
        name = request.POST["name"]
        email = request.POST["email"]
        phone = request.POST["phone"]
        home_address = request.POST["home_address"]
        contact_via = request.POST["contact_via"]
        memeber_type = request.POST["memeber_type"]
        current_job = request.POST["current_job"]
        if name:
            savemem = Memebers.objects.create(name=name, email=email, phone=phone, home_address=home_address,
                                              contact_via=contact_via, memeber_type=memeber_type, current_job=current_job)
            savemem.save()
            create_activity_stream(request.user, "New Member registered",
                               ref_id, 'Success', target=savemem)
            # update_activity_stream(
            #     ref_id, "Member registered Successfully", 'Success', user=request.user, target=savemem)
            return redirect('home')
        create_activity_stream(request.user, "New Member registered",
                               ref_id, 'Failed')
        # update_activity_stream(
        #     ref_id, "Member registered Failed", 'Failed', user=request.user)
    context = {"form": form}
    return render(request, 'multForm/member.html', context)

from django.utils.functional import LazyObject
from elasticsearch_dsl.query import Q
from django.contrib.contenttypes.models import ContentType
class SearchResults(LazyObject):
    def __init__(self, search_object):
        self._wrapped = search_object
    def __len__(self):
            return self._wrapped.count()
    def __getitem__(self, index):
        search_results = self._wrapped[index]
        if isinstance(index, slice):
            search_results = list(search_results)
        return search_results
    
    
@login_required(login_url='signin')
def home(request):
    # activitystreams = ActivityStream.objects.all()
    activitystreams=ActivitystreamDocument.search().sort('-created')
    username  = request.GET.get('username')
    email  = request.GET.get('email')
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    ctype = request.GET.get('ctype')
    print(ctype)
    search = ActivitystreamDocument.search().sort('-created')
    ctypes = ContentType.objects.all()
    
    if username:
        # activitystreams = activitystreams.filter(user__username__icontains=username)
        activitystreams=search.filter("match_phrase_prefix",user__username=username)
        for i in activitystreams:
            print(i)
    if email:
        activitystreams=activitystreams.filter("match_phrase_prefix", user__email=email)
    if start_date:
        activitystreams=activitystreams.filter("range", created={"gte": start_date})
    if end_date:
        activitystreams=activitystreams.filter("range", created={"lte": end_date})
    if ctype:
        activitystreams=activitystreams.filter("match", target=ctype)
            
    search_results = SearchResults(activitystreams)
    page = request.GET.get('page', 1)
    paginator = Paginator(search_results, 10)
    
    try:
        activitystreams = paginator.page(page)
    except PageNotAnInteger:
        activitystreams = paginator.page(1)
    except EmptyPage:
        activitystreams = paginator.page(paginator.num_pages) 
    context = {"activitystreams": activitystreams, "ctypes": ctypes}
    return render(request, 'multForm/home.html', context)
    #  if username:
    #         activitystreams = activitystreams.filter(user__username__icontains=username)
    # context = {"activitystreams": activitystreams}
    # return render(request, 'multForm/home.html', context)



@login_required(login_url='signin')
def member_details(request):
    members = Memebers.objects.all()
    name  = request.GET.get('name')
    email  = request.GET.get('email')
    if name:
        members = members.filter(name__icontains=name)
    if email:
        members = members.filter(email__icontains=email)
    page = request.GET.get('page', 1)

blogapp/templates/multForm/activity_stream_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<link rel = "stylesheet" href = "https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">

    <title>HOME PAGE</title>
</head>
<body>
    
    <p> <a href="{% url 'home' %}">Home</a> </p>
    <p> <a href="{% url 'register' %}">Register</a> </p>
    
    {% if request.user.is_authenticated %}
    <p> <a href="{% url 'signout' %}">Log out</a> </p>
    {% else %}
    <p> <a href="{% url 'signin' %}">Login</a> </p>
    {% endif %}
    
    <p> <a href="{% url 'main_index' %}">Register New comer</a> </p>

    <p> <a href="{% url 'member' %}">Member</a> </p>
    <p> <a href="{% url 'member-list' %}">Member List</a> </p>
    <p> <a href="{% url 'newcomer-list' %}">Newcomer List</a> </p>
    <h1>Home Page</h1>

    <p style="color:green">ACTIVITY STREAM</p>


   


<div style="margin:0 30px">
    <table id = "myTable" class = "table table-bordered" style = "width: 100%;">
        <thead>
        <tr>
        <th> S/N </th>    
        <th> User </th>

        <th> target_ct </th>
        <th> target_id </th>
        <th> target </th>
        <th>Created</th>
        <th>Created at</th>

        </tr>
        </thead>
        {% for activitystreamset in activitystreamsets %}
        <tbody>
            <tr>
            <td>{{forloop.counter}} </td>
            <td> <a href="{{ activitystreamset.activitystream }}">
                {{ activitystreamset.activity_stream.user.first_name }}
                {{ activitystreamset.activity_stream.user.last_name }}
              </a></td>
            <td> {{activitystreamset.target_ct}} </td>
            <td> {{ activitystreamset.target_id}} </td>
            <td> {{ activitystreamset.target.name }} </td>
            <td>{{ activitystreamset.created|timesince }} ago </td>
            <td>{{ activitystreamset.created}}</td>
            </tr>
            </tbody>
        {% endfor %}
       
        
        </table>


             
</div>














    <script src = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js</script>
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src = "https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src = "https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>


    <script>
    $(document).ready(function() {
    $('#myTable').DataTable();
    } );
    </script>
</body>
</html>

blogapp/templates/multForm/member_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<link rel = "stylesheet" href = "https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">

    <title>MEMBER LIST PAGE</title>
</head>
<body>
    
    <p> <a href="{% url 'home' %}">Home</a> </p>
    <p> <a href="{% url 'register' %}">Register</a> </p>
    
    {% if request.user.is_authenticated %}
    <p> <a href="{% url 'signout' %}">Log out</a> </p>
    {% else %}
    <p> <a href="{% url 'signin' %}">Login</a> </p>
    {% endif %}
    
    <p> <a href="{% url 'main_index' %}">Register New comer</a> </p>

    <p> <a href="{% url 'member' %}">Member</a> </p>
    <p> <a href="{% url 'member-list' %}">Member List</a> </p>
    <p> <a href="{% url 'newcomer-list' %}">Newcomer List</a> </p>
    <h1>MEMBER LIST PAGE</h1>

    <p style="color:green">ACTIVITY STREAM</p>


   <form method="GET" autocomplete="off" style="width: 20%; margin-left:70px;"> 
    <label class="kt-form-label">name</label>
    <div class="kt-form__control">
        <input type="text" class="form-control" name="name"
                {% if request.GET.name %}
                    value={{ request.GET.name }}
                {% endif %} id="id_name">
    </div>

    <label class="kt-form-label">email</label>
    <div class="kt-form__control">
        <input type="text" class="form-control" name="email"
                {% if request.GET.email %}
                    value={{ request.GET.email }}
                {% endif %} id="id_email">
    </div>
    <button style="background:blue; color:white; margin:10px" type="submit" class="btn btn-md kt-font-bold-lighter kt-bg-red-darken-4 kt-white-text kt-form__control">
    <i class="flaticon2-search-1"></i>Search</button>
   </form>


<div style="margin:0 30px">
    <table id = "myTable" class = "table table-bordered" style = "width: 100%;">
        <thead>
        <tr>
        <th>S/N</th>
        <th> Name </th>
        <th> Email </th>
        <th> Phone </th>
        <th>Created</th>
        <th>Created at</th>

        </tr>
        </thead>
        {% for member in members %}
        <tbody>
            <tr>
            <td>&nbsp;&nbsp;&nbsp;{{ forloop.counter }}</td>
            <td> {{ member.name}} </td>
            <td> {{ member.email }} </td>
            <td> {{ member.phone}} </td>
            <td> {{ member.created|timesince }} </td>
            <td> {{ member.created}} </td>


            
            </tr>
            </tbody>
        {% endfor %}
       
        
        </table>


              <!-- Activity Stream Pagination begins here -->
              {% if members %} 
              {% if members.has_other_pages %}
              <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
                  {% if members.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ members.previous_page_number }}" tabindex="-1">Previous</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                  </li>
                  {% endif %}
                  <li class="page-item"><a class="page-link">Page {{ members.number }} of {{ members.paginator.num_pages }}</a></li>
                  {% if members.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ members.next_page_number }}">Next</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" href="#" aria-disabled="true">Next</a>
                  </li>
                  {% endif %}
              </ul>
              </nav>
              {% endif %}
      {% endif %}
           
  <!--Activity Stream End of pagination -->
</div>














    <script src = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js</script>
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src = "https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src = "https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>


    <script>
    $(document).ready(function() {
    $('#myTable').DataTable();
    } );
    </script>
</body>
</html>

















{% comment %} 

from django_seed import Seed

seeder = Seed.seeder()

from blogapp.models import Members
seeder.add_entity(Memebers, 10000)
seeder.add_entity(Player, 10)

inserted_pks = seeder.execute() {% endcomment %}

blogapp/templates/multForm/newcomer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<link rel = "stylesheet" href = "https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">

    <title>MEMBER LIST PAGE</title>
  
</head>
<body>
    
    <p> <a href="{% url 'home' %}">Home</a> </p>
    <p> <a href="{% url 'register' %}">Register</a> </p>
    
    {% if request.user.is_authenticated %}
    <p> <a href="{% url 'signout' %}">Log out</a> </p>
    {% else %}
    <p> <a href="{% url 'signin' %}">Login</a> </p>
    {% endif %}
    
    <p> <a href="{% url 'main_index' %}">Register New comer</a> </p>

    <p> <a href="{% url 'member' %}">Member</a> </p>
    <p> <a href="{% url 'member-list' %}">Member List</a> </p>
    <p> <a href="{% url 'newcomer-list' %}">Newcomer List</a> </p>
    <h1>MEMBER LIST PAGE</h1>

    <p style="color:green">ACTIVITY STREAM</p>


   <form method="GET" autocomplete="off" style="width: 20%; margin-left:70px;"> 
    <label class="kt-form-label">name</label>
    <div class="kt-form__control">
        <input type="text" class="form-control" name="name"
                {% if request.GET.name %}
                    value={{ request.GET.name }}
                {% endif %} id="id_name">
    </div>

    <label class="kt-form-label">email</label>
    <div class="kt-form__control">
        <input type="text" class="form-control" name="email"
                {% if request.GET.email %}
                    value={{ request.GET.email }}
                {% endif %} id="id_email">
    </div>
    <button style="background:blue; color:white; margin:10px" type="submit" class="btn btn-md kt-font-bold-lighter kt-bg-red-darken-4 kt-white-text kt-form__control">
    <i class="flaticon2-search-1"></i>Search</button>
   </form>


<div style="margin:0 30px">
    <table id = "myTable" class = "table table-bordered" style = "width: 100%;">
        <thead>
        <tr>
        <th>S/N</th>
        <th> Name </th>
        <th> Email </th>
        <th> Phone </th>
        <th>Created</th>
        <th>Created at</th>

        </tr>
        </thead>
        {% for member in members %}
        <tbody>
            <tr>
            <td>&nbsp;&nbsp;&nbsp;{{ forloop.counter }}</td>
            <td> {{ member.name}} </td>
            <td> {{ member.email }} </td>
            <td> {{ member.phone}} </td>
            <td> {{ member.created|timesince }} </td>
            <td> {{ member.created}} </td>


            
            </tr>
            </tbody>
        {% endfor %}
       
        
        </table>


              <!-- Activity Stream Pagination begins here -->
              {% comment %} {% if members %} 
              {% if members.has_other_pages %}
              <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
                  {% if members.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ members.previous_page_number }}" tabindex="-1">Previous</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                  </li>
                  {% endif %}
                  <li class="page-item"><a class="page-link">Page {{ members.number }} of {{ members.paginator.num_pages }}</a></li>
                  {% if members.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ members.next_page_number }}">Next</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" href="#" aria-disabled="true">Next</a>
                  </li>
                  {% endif %}
              </ul>
              </nav>
              {% endif %}
      {% endif %} {% endcomment %}
           
  <!--Activity Stream End of pagination -->
</div>














    <script src = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js</script>
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src = "https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src = "https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>


    <script>
    $(document).ready(function() {
    $('#myTable').DataTable();
    } );
    </script>
</body>
</html>

















{% comment %} 

from django_seed import Seed

seeder = Seed.seeder()

from blogapp.models import Members
seeder.add_entity(Memebers, 10000)
seeder.add_entity(Player, 10)

inserted_pks = seeder.execute() {% endcomment %}